### ISSUE TITLE
vscode 'go to definition' doesn't work any more

### ISSUE THREAD

**Issue by djaonourside** [kLabz/haxe-react#30]
Haxe 4 rc 2, react-next 1.114. 
![pic1](https://user-images.githubusercontent.com/12369638/57134924-5b016300-6db0-11e9-9279-54e54831fe4e.png)
It works with react, git ref: "4126369a49019a3faed1f1f780532615ac319fe4".

**Comment by djaonourside** [comment]
vshaxe output:
```
Processing Arguments [--cwd,e:/projects/haxe/react-test/haxe-new-react,build.hxml,-D,display-details,--no-output,--display,{"jsonrpc":"2.0","id":441,"method":"display/definition","params":{"file":"e:/projects/haxe/react-test/haxe-new-react/src/Main.hx","contents":"import components.Hello;\r\nimport js.Browser;\r\nimport js.html.DivElement;\r\nimport react.ReactDOM;\r\nimport react.ReactMacro.jsx;\r\n\r\nclass Main\r\n{\r\n\tstatic var _root: DivElement;\r\n\t\r\n\tpublic static function main()\r\n\t{\r\n\t\tinitRoot();\r\n\t\trender();\r\n\t}\r\n\r\n\tstatic inline function initRoot()\r\n\t{\r\n\t\t_root = Browser.document.createDivElement();\r\n\t\tBrowser.document.body.appendChild(_root);\r\n\t}\r\n\t\r\n\tstatic function render() \r\n\t{\r\n\t\tReactDOM.render(jsx('\r\n\t\t\t<$Hello name=\"John\" />\r\n\t\t'), _root);\r\n\t}\r\n}","offset":454}}]
Defines dce=std,debug=1,display-details=1,display=1,display_details=1,display_stdin=1,haxe3=1,haxe4=1,haxe_ver=4.000,html-entities=1.0.0,html_entities=1.0.0,js-es5=1,js-object=0.0.6,js=1,js_es5=1,js_es=5,js_object=0.0.6,no_copt=1,react-next=1.114.0,react=1.114.0,react_hot=1,react_next=1.114.0,source-header=Generated by Haxe 4.0.0-rc.2+77068e10c,target.name=js,target.utf16=true,tink_anon=0.4.0,tink_core=1.22.0,tink_hxx=0.22.1,tink_macro=0.17.5,tink_parse=0.3.0,true=1,utf16=1
Using signature 3457dc9e7d6c2fa8c3140fa7d9c87ee8
Display position: e:\projects\haxe\react-test\haxe-new-react\src\main.hx: 454-454
 0, js: skipping Main
 0, js: parsed e:\projects\haxe\react-test\haxe-new-react\src\main.hx (not cached, is display file)
 0, js: skipping components.Hello
Stats = 1 files, 2 classes, 1 methods, 7 macros
Time spent : 0.038s
[Error - 14:46:42] Request textDocument/definition failed.
  Message: string constant expected
  Code: -32603 
```

**Comment by kLabz** [comment]
Indeed this works with react 1.5.0 but not with react-next.

I have the same results in the macro with both libs, and `Context.typeof()` finds the type correctly.

Maybe this has something to do with how tink_hxx works? cc @back2dos 

Minimal example (same result without quotes):
```haxe
import react.ReactMacro;
import react.Fragment;

class Main {
	static function main() {
		ReactMacro.jsx('<$Fragment />');
	}
}
```

**Comment by djaonourside** [comment]
@kLabz ,vscode 'go to definition' doesn't work with inline xml 
```haxe
import react.ReactMacro;
import react.Fragment;

class Main {
	static function main() {
		ReactMacro.jsx(<$Fragment />);
	}
}
```

**Comment by kLabz** [comment]
Yeah that's expected.. with strings it's resolved as string interpolation and "just works" but there's nothing with "not xml" =/

**Comment by back2dos** [comment]
You could try returning `MacroStringTools.formatString(v, expr.pos)` in the [markup branch](https://github.com/kLabz/haxe-react/blob/db0721082f29a784c03f988dae28458ef2e35f30/src/lib/react/ReactMacro.hx#L44). IIRC, you may need to adjust the position slightly.

@djaonourside personally, I advise against using inline markup, because it's an experimental feature with an unknown future. As you're using VSCode, I suggest using [Jeremy's "plugin"](https://github.com/jeremyfa/haxe-xmlgrammar) which will ultimately result in a better experience with more accurate and meaningful syntax highlighting.

**Comment by djaonourside** [comment]
@kLabz , @back2dos  Guys, thanks for replies : )
