### ISSUE TITLE
Compatibility with haxe-redux

### ISSUE THREAD

**Issue by djaonourside** [kLabz/haxe-react#33]
Is react-next compatible with haxe-redux? I get "Unknown identifier : context" in ConnectMacro.hx.

**Comment by djaonourside** [comment]
Oh, I've found 'react_deprecated_context' flag that solves it.

**Comment by djaonourside** [comment]
Rudy, how do you think if it's possible to reimplement haxe-redux with the actual context api?

**Comment by kLabz** [comment]
It's probably possible yeah, depends on what you need from redux I guess

**Comment by kLabz** [comment]
Oh and for your original question: current haxe-redux is in a delicate state, where you need to pick sides :

* downgrade/keep old version of react-redux and use IConnectedComponent and/or connect
* use Provider + IConnectedComponent only, without react-redux and without connect (which wouldn't work with recent react-redux)
* use ReactReduxProvider + connect, but IConnectedComponent will be broken with recent react-redux

`IConnectedComponent` indeed isn't really compatible with react-next / recent reactjs versions, though it can be made to work for now (indeed with `D react-deprecated-context`).

**Comment by djaonourside** [comment]
I like `IConnectedComponent` approach with it's `mapState` function and dispatch() auto-injecting. But it relies on the depricated context:(

**Comment by djaonourside** [comment]
By the way why the context field is under the deprecated flag? Actuact context api assumes this field presence https://reactjs.org/docs/context.html#classcontexttype

**Comment by kLabz** [comment]
It should be present in your component (with proper typing and static `contextType`), but not on ReactComponent itself.

Btw context is now (since version 0.5.2 released earlier today) being injected by haxe-redux itself when needed. I guess this closes this issue?

**Comment by djaonourside** [comment]
Yep! Thanks)
