### ISSUE TITLE
Allow extern class to extend class that extends Component

### ISSUE THREAD

**Issue by kevinresol** [kLabz/haxe-react#37]
To be clear, the following message should not apply to extern class.
``A react component must be a direct child of either `ReactComponent` or `PureComponent`.``

Because it is really what's happening in the underlying library, e.g:
https://github.com/uber/deck.gl/blob/9bdd6b7f0cafabe6d48275f59dcb7c3ba5777c8a/modules/layers/src/icon-layer/icon-layer.js#L69

https://github.com/uber/deck.gl/blob/9bdd6b7f0cafabe6d48275f59dcb7c3ba5777c8a/modules/core/src/lib/layer.js#L103

**Comment by kLabz** [comment]
I'm really not sure they're doing this right, but I don't really care. Externs not being a direct child class of ReactComponent shouldn't break macros. Probably.

Fixed in f0895f4
