### ISSUE TITLE
Is it possible to use styled-components and other react component libs?

### ISSUE THREAD

**Issue by linonetwo** [kLabz/haxe-react#40]
I'd like to use react for UI, using antd or blueprintjs for basic component, and styled-components for style adjustment.

I'm a react programmer, very new to haxe, may I ask is this inter-op easy?

**Comment by kLabz** [comment]
You'll have to write externs for the libs you use, but it's definitely possible. You can see examples [on haxelib](https://lib.haxe.org/search?v=react) (you may want to ignore react-native ones, they may work differently).

**Comment by linonetwo** [comment]
Thanks for your answer, I will consider is it easier to write externs or easier to use message channel to connect game and UI written in my familiar TSX app.
