### ISSUE TITLE
XML literal strings support

### ISSUE THREAD

**Issue by djaonourside** [kLabz/haxe-react#8]
Haxe 4.0.0-preview.5 has been released and it would be nice to have XML literal strings for jsx:)

**Comment by kLabz** [comment]
Yep but we would loose react fragments notation (`<>some jsx</>`) =/
I need to test some alternatives.

**Comment by kLabz** [comment]
Fragments could be handled with `<_> ... </_>` which is close enough imo.

But there is actually a real deal breaker: "xml" literals in haxe 4 preview 5 do not support tags starting with an uppercase letter (nor with a `$`), which is important for React.

I'll close this until next preview if it contains a parser that does the job =/

**Comment by djaonourside** [comment]
I've created the issue.
[https://github.com/HaxeFoundation/haxe/issues/7558](https://github.com/HaxeFoundation/haxe/issues/7558)
